import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the FontAwesome CSS
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser, faCog } from '@fortawesome/free-solid-svg-icons';
import "./globals.css";

export const metadata = {
  title: "Ali Abid Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
